### ISSUE TITLE
🚧Update issue and PR templates

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/GotNuget#10]
### I have done the items below . . .

- [x]  I have updated the title without removing the 🚧 emoji.

### Description

Update and improve project item issue template 

### Acceptance Criteria

**This issue is finished when:**
- Issue templates updated
  - [x]  bug-issue-template.yml updated
  - [x]  feature-request-issue-template.yml updated
  - [x]  release-todo-issue-template.yml updated
  - [x]  project-item-issue-template.yml updated
  - [x]  research-issue-template.yml updated
- PR templates updated and text `-template` added to the end of the file before the file extension
  - [x]  feature-pr.md
  - [x]  preview-feature-pr.md
  - [x]  preview-release-pr.md
  - [x]  production-release-pr.md
- [x] Add/update config.yml
- [x]  Update all URL's in all of the templates to match for the project

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [x] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [x] Issue linked to the proper project
- [x] Issue linked to proper milestone
