### ISSUE TITLE
🚧Add notes about Ubuntu to README 

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/GotNuget#18]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the `README.md` file by adding the following **Quick Note** section.  This text is about notifying the user that the action must be used in a job that runs on **Ubuntu**, not **Windows**.
Insert the markdown in between the **What is it?** and **Quick Example** sections.

**Markdown to add:**
```txt
<div align="center"><h3 style="font-weight:bold">⚠️Quick Note⚠️</h3></div>

This GitHub action is built using C#/NET and runs in a docker container.  If the job step for running this action is contained in a job that runs on **Windows**, you will need to move the step to a job that runs on **Ubuntu**.  You can split up your jobs to fulfill `runs-on` requirements of the GitHub action. This can be accomplished by moving the step into it's own job.  You can then route the action step outputs to the job outputs and use them throughout the rest of your workflow. For more information, refer to the Github documentation links below:

For more info on step and job outputs, refer to the GitHub documentation links below:
- [Defining outputs for jobs](https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs)
- [Setting a step action output parameter](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter)
```

**Old section to replace:**
![image](https://user-images.githubusercontent.com/85414302/185456392-ca8cd342-a6ef-4add-96cd-2ef36d15cb41.png)

### Acceptance Criteria

- [x] README file updated

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if required)_.
- [X] Issue linked to the correct milestone _(if required)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/GotNuget/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/GotNuget/labels/%F0%9F%A7%A8breaking%20changes      |
| New Feature         | https://github.com/KinsonDigital/GotNuget/labels/%E2%9C%A8new%20feature              |
| Workflow Changes    | https://github.com/KinsonDigital/GotNuget/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/GotNuget/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/GotNuget/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/GotNuget/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/GotNuget/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/GotNuget/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
