### ISSUE TITLE
🚧Setup CICD dotnet tool

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/GotNuget#30]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Setup the CICD dotnet tool for the project.

This will require creating a _**.nuke**_ directory with a **_parametes.json_** file as well as workflows.

> **Warning** The **_prev-release.yml_** and _**prod-release.yml**_ files need to be a little different than the generated ones.
> The reason is because CICD does not have the ability to collect code coverage and we are waiting for a release to get that feature.  Refer to the **VersionMiner** project as a reference to how it was setup.

### Acceptance Criteria

- [ ] CICD completely setup and working

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [ ] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
