### ISSUE TITLE
🚧Add badges to README

### ISSUE THREAD

**Issue by KinsonDigitalAdmin** [KinsonDigital/GotNuget#38]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add various badges to the README.  If any badges to be added match the ones used in the Velaptor project, use them as a reference.

Use [Shields IO](https://shields.io/) to create the badges.

### Acceptance Criteria

- [x] Add discord badge
- [x] Add good first issue badge
- [x] Build status
    > **Note** Use the GitHub Workflow Status (with branch) badge for build workflow
- [x] Unit test status
    > **Note** Use the GitHub Workflow Status (with branch) badge for unit test workflow

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by KinsonDigitalAdmin** [comment]
PR closed without merging. 

**Reason:** previous work from another PR indirectly fixed the badges
