### ISSUE TITLE
🚧Update workflows

### ISSUE THREAD

**Issue by KinsonDigitalAdmin** [KinsonDigital/GotNuget#39]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the _**build-status-check.yml**_ and _**unit-tests-status-check.yml**_ workflows by removing the ignored paths.

**Make these changes to both of the files:**
```diff
on:
  workflow_dispatch:
-    paths-ignore:
-      - ".github/**"
-      - "Documentation/**"
-      - '.editorconfig'
-      - '*.runsettings'
-      - '.gitattributes'
-      - '.gitignore'
-      - '*.md'
-      - '*.yml'
-      - '.vscode/**'
-      - '*.sln'
```

### Reason
The folder and file paths are currently locking the status checks into never being ran as long as the changes in a PR are included in the list of files and folders being ignored.

Here is an example of status checks locked.  They never get ran but prevent the PR from being merged unless merging is performed with admin bypass.
![image](https://user-images.githubusercontent.com/105235056/220634032-65869048-a2ba-4440-9d96-66b5287e2e43.png)

### Acceptance Criteria

- [x] _**build-status-check.yml**_ file updated
- [x] _**unit-tests-status-check.yml**_ file updated

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
