### ISSUE TITLE
🚧Convert to NugetExistsChecker to dotnet

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/GotNuget#4]
### I have done the items below . . .

- [X] I have created a title but left the 🚧 emoji behind.

### Description

Convert the project to a NET project.

### Acceptance Criteria

**This issue is finished when:**
- [x] Project converted
- [x] Make sure that the action works.
- [x] Unit tests created
- [x] Use the C# HTTP client [Rest Sharp](https://github.com/restsharp/RestSharp)
- [x] The name/ID of the package in the URL must be lowercase
  - Examples:
    - Good URL: https://api.nuget.org/v3-flatcontainer/`kinsondigital.casl`/index.json
    - Bad URL: https://api.nuget.org/v3-flatcontainer/ KinsonDigital.CASL/index.json

### ToDo Items

- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project

### Issue Dependencies

- #3

**Comment by CalvinWilkinson** [comment]
Issue complete and merged for version v1.0.0-preview.1
