### ISSUE TITLE
🚧Update Readme 

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/GotNuget#53]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

## **Description**

We are in the process of rationalizing ReadMe across all GitHub Actions (GHA). This includes:

Making sure all sections are in this order:
  - ~Logo added~
  - Repo Name
  - Badges
  - What is it
  - Quick Note
  - Quick Example
  - Action Input
  - Action Output
  - Examples
  - Contrib/Funding (after combined like in lib section)
  - Maintainers
  - License

### **Details of the changes to the sections are below:**
**Logo (CMW to create)**
> **Note** Calvin needs to create a logo from scratch.  

**Add Badges Section**
> **Note** Calvin will do this
- Good first issue
- Chat on discord
- ~Prod Build status~
- ~Prev build status~

**What is it Section**
- Use what is currently in this section after spelling and grammar checks
  
**Quick Note Section** 
- Change to say Warning block instead of Quick Note

**Quick Example Section**
- Make sure the "more examples below" link is on the right side.

**What does it do? Section**
- Remove section

**Action Input/Output Section**
- Add "Action Outputs" section, but do not add a table with the outputs in it. The output is a boolean value. Goes below Action Input section.
> **Note** Calvin will do this.

**Examples Section**
- Remove section
> **Note** Calvin will do: In the quick example at the top, add the optional `fail-when-not-found` input.  Make sure to add a quick note with a finger pointing emjoi to the right of the input to describe that it is optional.

**Contribution Section**
- Change title to Contributing
- Add section, make general (don't use repo or project name)
- To learn how to contribute your time click here (link to Contributing doc). To learn how to contribute funds to this project, click here.

**Maintainers Section**
- Add section like in Velaptor
- Remove "Project Maintainers" text and ancillary information.  The section should only be two lines: one for CMW and one for KSW

**License Section**
- Add section just like in Velaptor; with badges etc.

### **Other**
 - Double checking spelling/grammar
 - Making wording the same in similar sections
 - Make sure "Back to the Top" link is on the right
 - Remove any TODO comments
 - Verify all links work and point correctly

## Acceptance Criteria
- [x] Make sure all sections are in this order:
- [x] Logo logo and repo will change; no longer needed)
    - [x] Repo Name
    - [x] Badges
    - [x] What is it
    - [x] Quick Note
    - [x] Quick Example
    - [x] Action Input
    - [x] Action Output
    - [x] Examples
    - [x] Contrib/Funding (after combined like in lib section)
    - [x] Maintainers
    - [x] License
- ~Logo created and added~
   > **Note** Calvin needs to create a logo from scratch
- [x] Add Badges
    > **Note** Calvin will do this
    - [x] Good first issue
    - [x] Chat on discord
    - [x] ~Prod Build status~
    - [x] ~Prev build status~
- [x] Perform spelling and grammar checks in the **What is it** section
- [x] Change the **Quick Note** section to Warning block 
- [x] Move the **more examples below** link is to the right side.
- [x] Remove the **What does it do** section
- [x] An **Action Outputs** section is created below the **Action Inputs** table.
    > **Note** Calvin will do this.
- [x] Remove **Examples** section
    > **Note** Calvin will do this
    - [x] Add the optional `fail-when-not-found` input.
        > **Note** Make sure to add a quick note with a finger pointing emjoi to the right of the input to describe that it is optional.
- [x] Update the **Contibution Section**
  - [x] Change the **Contribution** title to **Contributing**
  - [x] Add one link that points to the Contributing doc for time contributions
    - [x] To learn how to contribute your time click `[here](https://github.com/KinsonDigital/.github/blob/master/docs/CONTRIBUTING.md)`
  - [x] Add one link that points to GitHub sponsors for monetary contributions
    - [x] To learn how to contribute funds to this project, click `[here](https://github.com/sponsors/KinsonDigital)`
  - [x] Add section, make general (don't use repo or project name)
- [x] Add **Maintainers** section like in Velaptor
  - [x] Remove "Project Maintainers" text and ancillary information.  The section should only be two lines: one for CMW and one for KSW
- [x] Add **License** section just like in Velaptor; with badges
 - [x] Double checking spelling/grammar
 - [x] Making wording the same in similar sections
 - [x] Make sure "Back to the Top" link is on the right
 - [x] Remove any TODO comments
 - [x] Verify all links work and point correctly

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
@kselena I added 2 badges but not the prod and prev status check badges.

The reason for this is because I have to create the workflows for these badges and they do not exist.  I also cannot create the workflows yet because we are changing the branching model for the all actions so that dictates how the workflows work.
