### ISSUE TITLE
🚧Rename project

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/GotNuget#71]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Rename the project from **GotNuget** to **PackageMonster**.

The reason for this is that the action will be used not only to check for Nuget packages for dotnet, but also npm packages.

### Acceptance Criteria

- [x] Rename process complete
  - [x] Repo renamed
  - [x] C# project renamed
  - [x] namespaces renamed
  - [x] comments renamed
  - [x] documentation (readme) updated
- [x] Need to design and setup a new logo

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
