### ISSUE TITLE
🚧Add ability to check for npm packages

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/GotNuget#72]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add the ability to check if npm packages exist.

This will require making calls to the npm registry using the URL `https://registry.npmjs.org`.

[Here](https://www.edoardoscibona.com/exploring-the-npm-registry-api) is a tutorial on some of it.
[Here](https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md#getpackageversion) is the official docs

### Acceptance Criteria

- [ ] Feature to check for npm packages created

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
