### ISSUE TITLE
🚧Add release note templates

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/GotNuget#9]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_\<title\>_**' section.

### Description
Add a preview and production release note template files.

### Acceptance Criteria

**This issue is finished when:**
- [x] Both preview and production templates are added

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [x] Priority label added to issue.  Refer to _**Change Type Labels**_ section below.
- [x] Issue linked to the proper project
- [x] Issue linked to proper milestone

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
